version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nestjs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - "4000:4000"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
