version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nestjs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - "4000:4000"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
