name: Run backend tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      working-directory: ./server
      run: npm install

    - name: Run tests
      working-directory: ./server
      run: npm run test
